apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - name: container-app-deployment
        image: talshaham/app-weather:65
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  selector:
    app: app-deployment
  ports:
  - name: http
    port: 80
    targetPort: 5000



