appDeployment:
  containerAppDeployment:
    image:
      repository: talshaham/app-weather
      tag: "65"
  replicas: 2
kubernetesClusterDomain: cluster.local
serviceApp:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: ClusterIP

ingress:
  host: a5ebb749041f94189a991edebceba222-1732078241.eu-north-1.elb.amazonaws.com
