apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  labels:
    app: weather-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: talshaham/app-weather:90
        env:
        - name: MONGO_HOST
          value: my-mongodb.default.svc.cluster.local

        - name: MONGO_PORT
          value: "27017"

        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongodb-root-username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongodb-root-password
---

apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
