apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 'ingress-app123'
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host  }}
    http:
      paths:
      - backend:
          service:
            name: 'weather-app-mychart-service-app'
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: 'weather-app-mychart-service-app'
            port:
              number: 80
        path: /static/* #for all the static files (css/images)
        pathType: Prefix
